/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.github.littleaj.marsroverimages;

public class App {

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
